name: 'publish'
on:
    push:
        branches:
            - master

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
            - uses: actions/checkout@v3

            - name: Build Changelog
              id: build_changelog
              run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install frontend dependencies
              run: pnpm install # change this to npm or pnpm depending on which one you use
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: 'Kiderat v__VERSION__'
                  releaseBody: |
                      ${{steps.build_changelog.outputs.changelog}}
                      See the assets to download this version and install.
                  releaseDraft: true
                  prerelease: false
